### ISSUE TITLE
Camarón-server

### ISSUE THREAD

**Issue by thucthattha** [ielijose/camaron-server#1]
call audio & call video
Error getting local media stream: PermissionDeniedError. Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).. Please enable requested media devices by clicking on the right hand icon in the address bar.
pls fix

**Comment by ielijose** [comment]
Hi @thucthattha,

use https:// instead http:// and try again.

**Comment by thucthattha** [comment]
can use http ??? i dont have https :(

2016-11-08 2:33 GMT+07:00 Eli José Carrasquero notifications@github.com:
